[[build.env]]
name = "GOOGLE_RUNTIME_VERSION"
value = "17"

[[build.env]]
name = "GOOGLE_FUNCTION_TARGET"
value = "jimlind.filmlinkd.Main"

[[build.env]]
name = "GOOGLE_ENTRYPOINT"
value = "java -jar target/filmlinkd.jar"
